// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerApi.Models;

#nullable disable

namespace TaskManagerApi.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    [Migration("20250323103529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerApi.Models.TaskItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("ReceivingTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsApproved = false,
                            ReceivingTeam = "Frontend",
                            RequestTeam = "DevOps",
                            Status = "Pending",
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2L,
                            IsApproved = true,
                            ReceivingTeam = "Frontend",
                            RequestTeam = "Backend",
                            ReviewMessage = "Reviewed and approved",
                            Status = "Active",
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = 3L,
                            IsApproved = false,
                            ReceivingTeam = "Test",
                            RequestTeam = "Frontend",
                            ReviewMessage = "Needs modifications",
                            Status = "Review",
                            Title = "Task 3"
                        },
                        new
                        {
                            Id = 4L,
                            IsApproved = true,
                            ReceivingTeam = "Backend",
                            RequestTeam = "DevOps",
                            Status = "Pending",
                            Title = "Task 4"
                        },
                        new
                        {
                            Id = 5L,
                            IsApproved = true,
                            ReceivingTeam = "DevOps",
                            RequestTeam = "Backend",
                            ReviewMessage = "Approved after review",
                            Status = "Active",
                            Title = "Task 5"
                        },
                        new
                        {
                            Id = 6L,
                            IsApproved = false,
                            ReceivingTeam = "Backend",
                            RequestTeam = "Frontend",
                            ReviewMessage = "Review pending",
                            Status = "Pending",
                            Title = "Task 6"
                        },
                        new
                        {
                            Id = 7L,
                            IsApproved = true,
                            ReceivingTeam = "Frontend",
                            RequestTeam = "DevOps",
                            ReviewMessage = "Reviewed successfully",
                            Status = "Review",
                            Title = "Task 7"
                        },
                        new
                        {
                            Id = 8L,
                            IsApproved = false,
                            ReceivingTeam = "Frontend",
                            RequestTeam = "Backend",
                            ReviewMessage = "In review process",
                            Status = "Pending",
                            Title = "Task 8"
                        },
                        new
                        {
                            Id = 9L,
                            IsApproved = true,
                            ReceivingTeam = "Backend",
                            RequestTeam = "Test",
                            Status = "Active",
                            Title = "Task 9"
                        },
                        new
                        {
                            Id = 10L,
                            IsApproved = false,
                            ReceivingTeam = "Test",
                            RequestTeam = "DevOps",
                            ReviewMessage = "Pending feedback",
                            Status = "Review",
                            Title = "Task 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
